2021/03/21 12:31:25 Attempt 1 of http call to http://10.0.0.7:16384/sendlogstoartifacts/info
2021/03/21 12:31:25 Attempt 1 of http call to http://10.0.0.7:16384/sendlogstoartifacts/status
[2021-03-21T12:31:26.509353] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['python train.py'])
Script type = COMMAND
[2021-03-21T12:31:28.153406] Command=python train.py
Starting the daemon thread to refresh tokens in background for process with pid = 107
[2021-03-21T12:31:28.322041] Entering Run History Context Manager.
[2021-03-21T12:31:29.074818] Command Working Directory=/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-141029/azureml/hd_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/mounts/workspaceblobstore/azureml/HD_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0
[2021-03-21T12:31:29.077849] Starting Linux command : python train.py
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from sklearn.linear_model import LogisticRegression
ModuleNotFoundError: No module named 'sklearn'
[2021-03-21T12:31:29.650824] Command finished with return code 1


[2021-03-21T12:31:29.653491] The experiment failed with exit code: 1. Finalizing run...
2021/03/21 12:31:30 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 1
FilteredData: 0.
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.47051095962524414 seconds
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-141029/azureml/hd_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/mounts/workspaceblobstore/azureml/HD_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/azureml-setup/context_manager_injector.py", line 448, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-141029/azureml/hd_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/mounts/workspaceblobstore/azureml/HD_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/azureml-setup/context_manager_injector.py", line 228, in execute_with_context
    process_return_code(signedReturnCode)
  File "/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-141029/azureml/hd_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/mounts/workspaceblobstore/azureml/HD_8c9c4fc6-09e4-4cfd-a630-9dc67c65cc03_0/azureml-setup/context_manager_injector.py", line 349, in process_return_code
    sys.exit(returnCode)
SystemExit: 1

[2021-03-21T12:31:30.765241] Finished context manager injector with SystemExit exception.
2021/03/21 12:31:31 Could not parse control script error at path: /mnt/batch/tasks/workitems/14d0ef3b-c24d-4539-94d7-e2b0f7fd5771/job-1/hd_8c9c4fc6-09e4-4cf_9367946c-9b68-425d-9a74-35e7bc1adab0/wd/runTaskLetTask_error.json because: File /mnt/batch/tasks/workitems/14d0ef3b-c24d-4539-94d7-e2b0f7fd5771/job-1/hd_8c9c4fc6-09e4-4cf_9367946c-9b68-425d-9a74-35e7bc1adab0/wd/runTaskLetTask_error.json doesn't exist, continuing without
2021/03/21 12:31:31 Failed to run the wrapper cmd with err: exit status 1
2021/03/21 12:31:31 Attempt 1 of http call to http://10.0.0.7:16384/sendlogstoartifacts/status
2021/03/21 12:31:32 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2021/03/21 12:31:32 MPI publisher: intel ; version: 2018
2021/03/21 12:31:32 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 2
FilteredData: 0.
2021/03/21 12:31:32 Process Exiting with Code:  1
